.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Daniel Patrick Abrecht <deb@danielabrecht.ch>,
.\"
.TH ckmvt 1 "September 15 2019"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
ckmvt \- Starts the console keyboard on a VT
.
.SH SYNOPSIS
.B ckmvt
vtnumber
.
.SH DESCRIPTION
This script starts console-keyboard-multiplexer(1) on the specified VT
