#!/bin/sh

[ "$1" = prereqs ] && exit 0 || true
[ -n "$CONSOLATION_PID" ] || exit 0

kill "$CONSOLATION_PID"

cat >/conf/param.conf <<EOF
kill $CONSOLATION_PID
unset CONSOLATION_PID
>/conf/param.conf
EOF

exit 0
