#!/bin/sh

nr="$(printf "%s" "$1" | /bin/sed 's/^tty//')"; shift

case "$nr" in
  *[!0-9]*)
    echo "Usage: $0 vtnumber"
    exit 1
  ;;
esac

tty="$(tty)"

if [ "$(tty)" != "/dev/tty$nr" ]
  then exec /sbin/getty -n -l "$0" -o "$nr $*" 38400 "tty$nr"
fi

exec /usr/bin/console-keyboard-multiplexer -w : -l "CKM$nr" -- login
