#!/bin/sh
set -e

[ "$1" = prereqs ] && exit 0 || true

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/consolation

for file in /usr/share/libinput/*.quirks
do
  copy_file libinput_quirk "$file" || true
done

for file in /lib/udev/libinput-* \
            /lib/udev/rules.d/*libinput*.rules \
            $(grep -rl ID_INPUT /lib/udev/rules.d/)
do
  copy_file libinput_udev "$file" || true
done

exit 0
