#!/bin/sh

[ "$1" = prereqs ] && exit 0 || true

# if another package calls update-initramfs -u before this package and the console-keyboard package is configured, the console-keyboard symlink would be missing and this script would fail.
# exit in this case, because this package will be configured again later
[ -h /usr/bin/console-keyboard ] || exit 0

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/console-keyboard-multiplexer
copy_exec /usr/bin/console-keyboard
copy_exec /usr/lib/libttymultiplex/backend-*/40-curses.so

copy_file terminfo /lib/terminfo/l/linux
copy_file terminfo /lib/terminfo/x/xterm

copy_exec /usr/bin/setsid
copy_exec /bin/sleep
copy_exec /bin/rm
copy_exec /bin/grep
copy_exec /bin/sed

# We only really need the C.UTF-8 locale, but whatever...
for localefile in $(find /usr/lib/locale/C.UTF-8 -type f)
do
  copy_file locale "$localefile"
done

exit 0
