#!/bin/sh
set -e

[ "$1" = prereqs ] && exit 0 || true

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/consolation

for file in /usr/share/libinput/*.quirks
do
  copy_file libinput_quirk "$file" || true
done

exit 0
